version: '2'
services:
    laravel:
        image: laravel:5.6-apache
        ports:
            - 8080:80
        environment:
            - TOYBOX_UID=1000
            - TOYBOX_GID=1000
            - ALL_PHP_MODULES=enable
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
            - LARAVEL_TZ=Asia/Tokyo
            - LARAVEL_LOCALE=ja
        volumes:
            - "./data/laravel:/var/www/laravel"
            - "./data/apache-conf:/etc/apache2"

    mariadb:
        image: nutsllc/toybox-mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
        volumes:
            - "./data/mysql:/var/lib/mysql"
