version: '2'
services:
    apache2:
        image: nutsllc/toybox-apache2:2.4
        environment:
            - TOYBOX_UID=1000
            - TOYBOX_GID=1000
        volumes_from:
            - data
        ports:
            - "8080:80"
    
    data:
        image: busybox
        volumes:
            - "./data/docroot:/usr/local/apache2/htdocs"
